# Generated by Django 5.2 on 2025-04-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_senha_usuario_password_usuario_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
            ],
        ),
    ]
