# Generated by Django 5.2 on 2025-05-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_modeloveiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='origem',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario',
            field=models.CharField(default='desconhecido', max_length=100),
            preserve_default=False,
        ),
    ]
