# Generated by Django 5.2 on 2025-05-04 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_veiculo_origem_veiculo_proprietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='A placa deve estar no formato AAA1234 (3 letras seguidas de 4 letras/números)', regex='^[A-Z]{3}[0-9A-Z]{4}$')]),
        ),
    ]
